// Code OS v2: durable run/task/event API. This is intentionally separate from
// the legacy pipeline so existing branches can migrate without data loss.
//
// This module is the parallel execution engine: unlike codePipeline.ts, which
// can only ever run one agent at a time because state lives on the single
// shared codeBranches row, every task here has its own row and its own
// status, so several can be "running" concurrently. Parallelism comes from
// scheduling one runTask action per ready task via ctx.scheduler.runAfter(0,
// ...) — never from Promise.all inside one action, which would risk the
// 10-minute action ceiling the moment two slow model calls land in the same
// invocation.
//
// A task is a LOOP, not one model call: write code, run the build, read the
// output, fix it, repeat. Commands are how a task verifies its own work, and
// they are per-task here rather than branch-scoped — the legacy pipeline parks
// the whole branch on "paused" for a command, which is precisely what stops it
// running two agents at once. The executors needed no change: both claim
// pending commands BY BRANCH, so a parallel run's commands are picked up as-is.
//
// Known limitation, unchanged: two tasks writing the same file is
// last-write-wins. Convex serializes the individual writes, but nothing
// arbitrates the intent, so the plan giving each task a disjoint set of files
// is the only real defence. MCP tool calls are still legacy-pipeline only.
import { mutation, query, internalMutation, internalAction, internalQuery, type QueryCtx } from "./_generated/server";
import { makeFunctionReference } from "convex/server";
import { internal } from "./_generated/api";
import { v } from "convex/values";
import type { Doc, Id } from "./_generated/dataModel";
import { assertBranchOwner, requireSession } from "./lib/codeAuth";
import { callModel } from "./lib/agentCore";
import { scheduleRun, type SchedulableTask } from "./lib/runScheduler";
import { parseAgentOutput, parsePlannerOutput } from "./lib/agentOutputParser";
import { orderPlannerTasks } from "./lib/taskGraph";
import {
  ORCHESTRATOR_SYSTEM_PROMPT,
  buildOrchestratorPrompt,
  buildTaskPrompt,
  normalizeAgent,
  renderCommandResults,
  renderCommandsUnavailable,
  systemPromptFor,
} from "./lib/parallelAgents";

// Self-references, made by string instead of through `internal.codeOrchestrator`
// — same fix as mcpServers.ts's refreshServerToolsRef. There the typed path
// trips the TS2589 instantiation-depth cliff; here it fails even earlier,
// because this module (added after the committed _generated/api.d.ts was last
// regenerated by `npx convex dev`) isn't in that generated type at all, so
// `internal.codeOrchestrator` is a flat TS2339 "does not exist". Either way
// the string path resolves identically at runtime and check-refs.mjs verifies
// it by name, kind and visibility just like a typed reference.
const dispatchReadyRef = makeFunctionReference<"mutation", { runId: Id<"codeRuns"> }>(
  "codeOrchestrator:dispatchReady",
);
const runTaskRef = makeFunctionReference<"action", { runId: Id<"codeRuns">; taskId: Id<"codeTasks"> }>(
  "codeOrchestrator:runTask",
);
const finishTaskRef = makeFunctionReference<
  "mutation",
  { runId: Id<"codeRuns">; taskId: Id<"codeTasks">; status: "completed" | "failed"; result: string }
>("codeOrchestrator:finishTask");
const getTaskContextRef = makeFunctionReference<
  "query",
  { runId: Id<"codeRuns">; taskId: Id<"codeTasks"> },
  {
    run: Doc<"codeRuns">;
    task: Doc<"codeTasks">;
    dependencies: Doc<"codeTasks">[];
    files: { filepath: string; content: string }[];
  } | null
>("codeOrchestrator:getTaskContextInternal");
const planRunRef = makeFunctionReference<"action", { runId: Id<"codeRuns"> }>(
  "codeOrchestrator:planRun",
);
const getRunContextRef = makeFunctionReference<
  "query",
  { runId: Id<"codeRuns"> },
  { run: Doc<"codeRuns">; files: { filepath: string; content: string }[] } | null
>("codeOrchestrator:getRunContextInternal");
const savePlanRef = makeFunctionReference<
  "mutation",
  {
    runId: Id<"codeRuns">;
    tasks: { id: string; title: string; description?: string; agent: string; dependencies: string[] }[];
    summary: string;
  }
>("codeOrchestrator:savePlan");
const failRunRef = makeFunctionReference<"mutation", { runId: Id<"codeRuns">; reason: string }>(
  "codeOrchestrator:failRun",
);
const answerRunRef = makeFunctionReference<"mutation", { runId: Id<"codeRuns">; answer: string }>(
  "codeOrchestrator:answerRun",
);
const queueTaskCommandsRef = makeFunctionReference<
  "mutation",
  { branchId: string; taskId: Id<"codeTasks">; agent: string; commands: string[] },
  Id<"codeCommands">[]
>("codeOrchestrator:queueTaskCommands");
const getTaskCommandsRef = makeFunctionReference<
  "query",
  { ids: Id<"codeCommands">[] },
  { command: string; status: string; output?: string; exitCode?: number }[]
>("codeOrchestrator:getTaskCommandsInternal");

// Cap on tasks dispatched at once per run. Every concurrent task is a live
// model call, and the provider chain (lib/agentCore.ts) has shared rate
// limits and learned cooldowns (lib/providerCooldowns.ts) that apply
// platform-wide, across every run and the live pipeline — not per run. Letting
// one run's plan fan out without bound would hammer every seat at once and
// trip cooldowns for everything else sharing the chain. 4 keeps a single
// run's burst well inside what a free-tier seat tolerates.
const MAX_CONCURRENT_TASKS = 4;

// A task's whole loop lives inside ONE action, so Convex's 10-minute kill is
// the real ceiling — not maxTurns. Every budget below is measured against the
// action's own start so a task always finishes deliberately, writing down what
// it did, instead of being killed mid-turn and leaving the row in "running"
// until finishTask never comes.
const TASK_WALL_CLOCK_MS = 8 * 60 * 1000;
const TURN_MODEL_DEADLINE_MS = 3 * 60 * 1000;
const COMMAND_WAIT_MS = 3 * 60 * 1000;
// Below this there is not enough left for a model call worth making.
const MIN_TURN_MS = 45 * 1000;
const COMMAND_POLL_MS = 4000;
// Plans are written by a model, so maxTurns is clamped rather than trusted.
const DEFAULT_TASK_TURNS = 4;
const MAX_TASK_TURNS = 8;

const TERMINAL_RUN_STATUSES = new Set(["completed", "cancelled", "failed"]);

function toSchedulable(tasks: Doc<"codeTasks">[]): SchedulableTask[] {
  return tasks.map((t) => ({ id: t._id, status: t.status, dependencies: t.dependencies }));
}

// The branch's files, which are what every agent reads and writes. Same store
// the legacy pipeline uses, so a run here and a run there see one project.
async function branchFiles(ctx: QueryCtx, branchId: string) {
  const rows = await ctx.db
    .query("codeFiles")
    .withIndex("by_branch", (q) => q.eq("branchId", branchId))
    .take(1000);
  return rows.map((r) => ({ filepath: r.filepath, content: r.content }));
}

// Waits for a task's own commands, and answers "what happened" rather than
// throwing. A command that never gets picked up is a real outcome the agent
// has to be told about — silence would have it assume success.
async function waitForCommands(
  ctx: { runQuery: (ref: typeof getTaskCommandsRef, args: { ids: Id<"codeCommands">[] }) => Promise<{ command: string; status: string; output?: string; exitCode?: number }[]> },
  ids: Id<"codeCommands">[],
  budgetMs: number,
) {
  const until = Date.now() + budgetMs;
  let last = await ctx.runQuery(getTaskCommandsRef, { ids });
  while (Date.now() < until) {
    if (last.every((r) => r.status === "completed" || r.status === "failed")) return last;
    await new Promise((r) => setTimeout(r, COMMAND_POLL_MS));
    last = await ctx.runQuery(getTaskCommandsRef, { ids });
  }
  // Out of time. Report what each command actually reached — a still-pending
  // command is not a passing one, and the agent is told so in those words.
  return last;
}

export const startRun = mutation({
  args: {
    token: v.string(),
    branchId: v.string(),
    prompt: v.string(),
    // Optional pre-built plan. Ids are plain strings chosen by whatever
    // produced the plan; they exist only to express dependencies before real
    // Convex ids exist and are translated below. Omitted on the normal path —
    // the run plans itself (planRun) from the prompt.
    plan: v.optional(
      v.array(
        v.object({
          id: v.string(),
          title: v.string(),
          description: v.optional(v.string()),
          agent: v.optional(v.string()),
          dependencies: v.optional(v.array(v.string())),
        }),
      ),
    ),
  },
  handler: async (ctx, args) => {
    const session = await requireSession(ctx, args.token);
    const { branch } = await assertBranchOwner(ctx, session.userId, args.branchId);
    const now = Date.now();
    // "auto" is the only mode. `ask` and `read_only` were modelled and never
    // implemented, and a run that stops to ask is the human-in-the-loop this
    // engine exists to remove — the column stays in the schema for old rows,
    // but nothing writes anything else.
    const runId = await ctx.db.insert("codeRuns", { branchId: args.branchId, projectId: branch.projectId, userId: session.userId, prompt: args.prompt.trim(), status: "queued", permissionMode: "auto", createdAt: now, updatedAt: now });

    if (args.plan && args.plan.length > 0) {
      // Pass 1: insert every task so a real Convex id exists for each plan
      // entry, then pass 2 translates each entry's string-id dependencies into
      // those real ids. An entry naming a dependency id outside the plan is
      // dropped rather than failing the insert — a typo in a model-authored
      // plan should not sink the run before it starts.
      const idMap = new Map<string, Id<"codeTasks">>();
      const inserted: { taskId: Id<"codeTasks">; dependsOn: string[] }[] = [];
      for (const entry of args.plan) {
        const taskId = await ctx.db.insert("codeTasks", {
          runId,
          title: entry.title,
          description: entry.description,
          agent: normalizeAgent(entry.agent ?? "Coder"),
          status: "queued",
          dependencies: [],
          allowedTools: ["filesystem", "terminal", "mcp"],
          maxTurns: 12,
          createdAt: now,
          updatedAt: now,
        });
        idMap.set(entry.id, taskId);
        inserted.push({ taskId, dependsOn: entry.dependencies ?? [] });
      }
      for (const { taskId, dependsOn } of inserted) {
        const resolved = dependsOn
          .map((depId) => idMap.get(depId))
          .filter((id): id is Id<"codeTasks"> => id !== undefined);
        if (resolved.length > 0) await ctx.db.patch(taskId, { dependencies: resolved });
      }
      await ctx.db.insert("codeRunEvents", { runId, type: "run.created", content: `Run created with a ${args.plan.length}-task plan.`, createdAt: now });
      await ctx.scheduler.runAfter(0, dispatchReadyRef, { runId });
      return { runId };
    }

    // The normal path: no plan was handed in, so the run builds its own. That
    // is a model call, which a mutation cannot make — planRun (an action) does
    // it and writes the tasks back. Planning is the ONLY sequential step in a
    // run; everything after it is decided by the dependency graph.
    await ctx.db.insert("codeRunEvents", { runId, type: "run.created", content: "Run created — planning.", createdAt: now });
    await ctx.scheduler.runAfter(0, planRunRef, { runId });
    return { runId };
  },
});

export const listRuns = query({ args: { token: v.string(), branchId: v.string() }, handler: async (ctx, args) => {
  const session = await requireSession(ctx, args.token); await assertBranchOwner(ctx, session.userId, args.branchId);
  return await ctx.db.query("codeRuns").withIndex("by_branch", q => q.eq("branchId", args.branchId)).order("desc").take(50);
} });

export const getRunBoard = query({ args: { token: v.string(), runId: v.id("codeRuns") }, handler: async (ctx, args) => {
  const session = await requireSession(ctx, args.token); const run = await ctx.db.get(args.runId); if (!run || run.userId !== session.userId) return null;
  const [tasks, events] = await Promise.all([ctx.db.query("codeTasks").withIndex("by_run", q => q.eq("runId", args.runId)).collect(), ctx.db.query("codeRunEvents").withIndex("by_run", q => q.eq("runId", args.runId)).order("desc").take(100)]);
  return { run, tasks, events: events.reverse() };
} });

export const cancelRun = mutation({ args: { token: v.string(), runId: v.id("codeRuns") }, handler: async (ctx, args) => {
  const session = await requireSession(ctx, args.token); const run = await ctx.db.get(args.runId); if (!run || run.userId !== session.userId) throw new Error("Run not found"); const now = Date.now();
  await ctx.db.patch(run._id, { status: "cancelled", cancellationRequested: true, updatedAt: now });
  await ctx.db.insert("codeRunEvents", { runId: run._id, type: "run.cancelled", content: "Cancelled by user.", createdAt: now });
} });

// Loads a run and its tasks, asks lib/runScheduler which tasks are ready to
// run right now, and acts on that decision. Re-entered by finishTask every
// time a task completes, which is what actually drives a run to completion —
// each dispatch only starts what is newly unblocked.
export const dispatchReady = internalMutation({
  args: { runId: v.id("codeRuns") },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (!run) return;
    // A terminal run is done; a cancelled-but-not-yet-terminal run must not
    // pick up new work either — cancelRun already stamped both status and
    // cancellationRequested together, but this checks both defensively so a
    // future caller that sets one without the other still can't resurrect it.
    if (TERMINAL_RUN_STATUSES.has(run.status) || run.cancellationRequested) return;

    const tasks = await ctx.db.query("codeTasks").withIndex("by_run", (q) => q.eq("runId", args.runId)).collect();
    const byId = new Map<string, Doc<"codeTasks">>();
    for (const t of tasks) byId.set(t._id, t);

    const decision = scheduleRun(toSchedulable(tasks), {
      maxConcurrent: MAX_CONCURRENT_TASKS,
      cancellationRequested: run.cancellationRequested ?? false,
    });
    const now = Date.now();

    for (const id of decision.ready) {
      const task = byId.get(id);
      if (task) await ctx.db.patch(task._id, { status: "running", updatedAt: now });
    }
    for (const id of decision.block) {
      const task = byId.get(id);
      if (task) await ctx.db.patch(task._id, { status: "blocked", updatedAt: now });
    }
    for (const id of decision.ready) {
      const task = byId.get(id);
      if (task) await ctx.scheduler.runAfter(0, runTaskRef, { runId: args.runId, taskId: task._id });
    }

    await ctx.db.insert("codeRunEvents", {
      runId: args.runId,
      type: "run.dispatch",
      content: `Dispatched ${decision.ready.length} task(s); blocked ${decision.block.length}.`,
      createdAt: now,
    });

    if (decision.stuck) {
      // A deadlocked run (dependencies that can never all be satisfied, or a
      // cycle) must end loudly, never sit at "running" with nothing in
      // flight forever.
      await ctx.db.patch(run._id, { status: "failed", updatedAt: now });
      await ctx.db.insert("codeRunEvents", {
        runId: args.runId,
        type: "run.stuck",
        content: `Run deadlocked — no task can make progress. Stuck task ids: ${decision.stuckIds.join(", ") || "(none)"}.`,
        createdAt: now,
      });
      return;
    }

    await ctx.db.patch(run._id, { status: decision.runStatus, updatedAt: now });

    // A blocking cascade has to be driven, not just started. finishTask is the
    // only other thing that re-enters this mutation, and a blocked task never
    // finishes — so a dispatch that blocked tasks without starting any would
    // be the last one to ever run. Left there, a failure's grandchildren stay
    // "queued" forever under a run still reading "running" with nothing in
    // flight, which is precisely the hang the stuck branch above exists to
    // prevent, reached by the other path. runScheduler resolves one dependency
    // level per call by design, so the loop has to come from here.
    if (decision.block.length > 0) {
      await ctx.scheduler.runAfter(0, dispatchReadyRef, { runId: args.runId });
    }
  },
});

export const getRunContextInternal = internalQuery({
  args: { runId: v.id("codeRuns") },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (!run) return null;
    return { run, files: await branchFiles(ctx, run.branchId) };
  },
});

// Turns the Planner's JSON into task rows. Ids in the plan are the Planner's
// own strings; they become real Convex ids here, in the same two passes
// startRun uses and for the same reason — dependencies are typed
// v.id("codeTasks") and no id exists until its row is inserted.
export const savePlan = internalMutation({
  args: {
    runId: v.id("codeRuns"),
    tasks: v.array(
      v.object({
        id: v.string(),
        title: v.string(),
        description: v.optional(v.string()),
        agent: v.string(),
        dependencies: v.array(v.string()),
      }),
    ),
    summary: v.string(),
  },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (!run) return;
    if (TERMINAL_RUN_STATUSES.has(run.status) || run.cancellationRequested) return;
    const now = Date.now();

    const idMap = new Map<string, Id<"codeTasks">>();
    const inserted: { taskId: Id<"codeTasks">; dependsOn: string[] }[] = [];
    for (const t of args.tasks) {
      const taskId = await ctx.db.insert("codeTasks", {
        runId: args.runId,
        title: t.title,
        description: t.description,
        agent: t.agent,
        status: "queued",
        dependencies: [],
        allowedTools: ["filesystem"],
        maxTurns: 1,
        createdAt: now,
        updatedAt: now,
      });
      idMap.set(t.id, taskId);
      inserted.push({ taskId, dependsOn: t.dependencies });
    }
    for (const { taskId, dependsOn } of inserted) {
      const resolved = dependsOn
        .map((d) => idMap.get(d))
        .filter((id): id is Id<"codeTasks"> => id !== undefined && id !== taskId);
      if (resolved.length > 0) await ctx.db.patch(taskId, { dependencies: resolved });
    }

    await ctx.db.patch(args.runId, { summary: args.summary, updatedAt: now });
    await ctx.db.insert("codeRunEvents", {
      runId: args.runId,
      type: "run.planned",
      content: `Plan ready — ${args.tasks.length} task(s). ${args.summary}`,
      createdAt: now,
    });
    await ctx.scheduler.runAfter(0, dispatchReadyRef, { runId: args.runId });
  },
});

// The answer exit: the request was a question, so the run completes with no
// tasks at all. It is still a run row with an event, because someone who asked
// a question should find the answer in the same place as every other result
// rather than have it vanish.
export const answerRun = internalMutation({
  args: { runId: v.id("codeRuns"), answer: v.string() },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (!run || TERMINAL_RUN_STATUSES.has(run.status) || run.cancellationRequested) return;
    const now = Date.now();
    await ctx.db.patch(args.runId, { status: "completed", summary: args.answer, updatedAt: now });
    await ctx.db.insert("codeRunEvents", {
      runId: args.runId,
      type: "run.answered",
      content: args.answer,
      createdAt: now,
    });
  },
});

// A run that cannot be planned has to end saying so. Silence here would leave
// a run "queued" with no tasks and nothing scheduled — invisible forever.
export const failRun = internalMutation({
  args: { runId: v.id("codeRuns"), reason: v.string() },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (!run || TERMINAL_RUN_STATUSES.has(run.status)) return;
    const now = Date.now();
    await ctx.db.patch(args.runId, { status: "failed", updatedAt: now });
    await ctx.db.insert("codeRunEvents", { runId: args.runId, type: "run.failed", content: args.reason, createdAt: now });
  },
});

// Planning: the one sequential step. Everything after it is decided by the
// dependency graph, so this is where a run's parallelism is won or lost — a
// plan that chains every task is a turn-wise pipeline wearing a graph's
// clothes, which is what lib/parallelAgents.ts's planner prompt pushes against.
export const planRun = internalAction({
  args: { runId: v.id("codeRuns") },
  handler: async (ctx, args) => {
    try {
      const context = await ctx.runQuery(getRunContextRef, { runId: args.runId });
      if (!context) return;
      const { run, files } = context;
      if (TERMINAL_RUN_STATUSES.has(run.status) || run.cancellationRequested) return;

      const result = await callModel(
        buildOrchestratorPrompt(run.prompt, files),
        ORCHESTRATOR_SYSTEM_PROMPT,
        "Planner",
        ctx,
      );

      // Two exits, and which one was taken is read off the output itself. A
      // JSON plan means build it; prose means the request was a question and
      // is already answered. Not every request is a project — "why is my build
      // failing" wants an answer, not a five-task plan with a Tester on it.
      const parsed = parsePlannerOutput(result.text);
      if (!parsed || parsed.tasks.length === 0) {
        const answer = result.text.trim();
        if (!answer) {
          await ctx.runMutation(failRunRef, {
            runId: args.runId,
            reason: "The orchestrator returned nothing — no answer and no plan.",
          });
          return;
        }
        await ctx.runMutation(answerRunRef, { runId: args.runId, answer });
        return;
      }

      // Sorting into dependency order is not required for correctness — the
      // scheduler reads the graph, not the array — but it makes the board read
      // top-to-bottom, and it is where a cycle or a dangling id gets caught
      // before it becomes a stuck run.
      const ordered = orderPlannerTasks(parsed.tasks);
      await ctx.runMutation(savePlanRef, {
        runId: args.runId,
        summary: parsed.summary || "Plan ready.",
        tasks: ordered.tasks.map((t, i) => ({
          id: String(t.id ?? `t${i}`),
          title: String(t.title ?? `Task ${i + 1}`).slice(0, 300),
          description: t.description ? String(t.description) : undefined,
          agent: normalizeAgent(String((t as { agent?: string }).agent ?? "Coder")),
          dependencies: (t.dependencies ?? []).map(String),
        })),
      });
    } catch (err) {
      await ctx.runMutation(failRunRef, {
        runId: args.runId,
        reason: `Planning failed: ${err instanceof Error ? err.message : String(err)}`,
      });
    }
  },
});

// Queues a task's commands and hands back their ids. The executors are not
// touched: both the GitHub Actions worker (claimPendingCommandsForVm) and the
// desktop local executor (listPendingForBranch) claim by BRANCH, so a parallel
// run's commands are picked up with no change to either. The taskId exists for
// the other direction — several tasks can have commands in flight on one branch
// at once, and each needs to recognise its own results.
export const queueTaskCommands = internalMutation({
  args: {
    branchId: v.string(),
    taskId: v.id("codeTasks"),
    agent: v.string(),
    commands: v.array(v.string()),
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    const ids: Id<"codeCommands">[] = [];
    for (const command of args.commands) {
      ids.push(
        await ctx.db.insert("codeCommands", {
          branchId: args.branchId,
          taskId: args.taskId,
          agent: args.agent,
          command,
          status: "pending",
          createdAt: now,
        }),
      );
    }
    return ids;
  },
});

export const getTaskCommandsInternal = internalQuery({
  args: { ids: v.array(v.id("codeCommands")) },
  handler: async (ctx, args) => {
    const rows = await Promise.all(args.ids.map((id) => ctx.db.get(id)));
    return rows
      .filter((r): r is Doc<"codeCommands"> => r !== null)
      .map((r) => ({
        command: r.command,
        status: r.status,
        output: r.output,
        exitCode: r.exitCode,
      }));
  },
});

// Read-only lookup an action needs to build a task's prompt: the run, the
// task itself, and the completed dependency tasks whose results feed it.
export const getTaskContextInternal = internalQuery({
  args: { runId: v.id("codeRuns"), taskId: v.id("codeTasks") },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    const task = await ctx.db.get(args.taskId);
    if (!run || !task || task.runId !== args.runId) return null;
    const dependencies = (await Promise.all(task.dependencies.map((id) => ctx.db.get(id)))).filter(
      (d): d is Doc<"codeTasks"> => d !== null,
    );
    return { run, task, dependencies, files: await branchFiles(ctx, run.branchId) };
  },
});

// Executes exactly one task's agent turn. This is the unit of concurrency:
// dispatchReady schedules one of these per ready task, so N scheduled actions
// is how N tasks actually run at the same time.
export const runTask = internalAction({
  args: { runId: v.id("codeRuns"), taskId: v.id("codeTasks") },
  handler: async (ctx, args) => {
    const startedAt = Date.now();
    const remainingMs = () => TASK_WALL_CLOCK_MS - (Date.now() - startedAt);
    try {
      const context = await ctx.runQuery(getTaskContextRef, args);
      if (!context) return; // run or task vanished (e.g. deleted mid-flight) — nothing to execute
      const { run, task, dependencies, files } = context;

      // Cancellation can land between dispatch and this action starting. The
      // model call is the expensive part of a run, so check before spending it
      // rather than discarding the answer afterwards.
      if (TERMINAL_RUN_STATUSES.has(run.status) || run.cancellationRequested) return;

      const agent = normalizeAgent(task.agent);
      const basePrompt = buildTaskPrompt({
        goal: run.prompt,
        title: task.title,
        description: task.description,
        // Only completed dependencies carry a usable report. A failed or
        // blocked one has nothing to hand over, and the scheduler would not
        // have started this task behind it anyway.
        upstream: dependencies
          .filter((d) => d.status === "completed")
          .map((d) => ({ title: d.title, agent: d.agent, result: d.result })),
        files,
      });

      // A task is a LOOP, not a single call: write code, run the build, read
      // the output, fix it. That loop is the whole reason commands exist here —
      // without it an agent can only claim its work is correct. maxTurns is the
      // per-task bound; the wall clock is the real one, because this action
      // dies at Convex's 10-minute ceiling regardless of turns remaining.
      const maxTurns = Math.min(Math.max(task.maxTurns || DEFAULT_TASK_TURNS, 1), MAX_TASK_TURNS);
      const wrote = new Set<string>();
      const removed = new Set<string>();
      const reports: string[] = [];
      let feedback = "";
      let executorReady: boolean | null = null;

      for (let turn = 1; turn <= maxTurns; turn++) {
        if (remainingMs() < MIN_TURN_MS) break;

        const result = await callModel(
          feedback ? `${basePrompt}\n\n${feedback}` : basePrompt,
          systemPromptFor(agent),
          agent,
          ctx,
          { deadlineMs: Math.min(TURN_MODEL_DEADLINE_MS, Math.max(remainingMs() - COMMAND_WAIT_MS, MIN_TURN_MS)) },
        );

        // This is where a task stops being prose and becomes work. Everything
        // that is not a file block or an op stays as the report dependents read.
        const parsed = parseAgentOutput(result.text, agent);
        for (const op of parsed.fileOps) {
          if (op.type === "delete") {
            await ctx.runMutation(internal.codeBranches.deleteFileByPath, {
              branchId: run.branchId,
              filepath: op.filepath,
            });
            removed.add(op.filepath);
            continue;
          }
          // A file op the parser could not give content for is a malformed op,
          // not a request for an empty file — writing "" would silently blank a
          // real file the agent meant to edit.
          if (typeof op.content !== "string") continue;
          await ctx.runMutation(internal.codeBranches.upsertFile, {
            branchId: run.branchId,
            filepath: op.filepath,
            content: op.content,
            agent,
          });
          wrote.add(op.filepath);
        }
        if (parsed.cleanContent.trim()) reports.push(parsed.cleanContent.trim());

        const commands = parsed.cmdOps.map((c) => c.command).filter((c) => c && c.trim());
        if (commands.length === 0) break; // nothing left to verify — the task is done talking
        if (turn === maxTurns || remainingMs() < COMMAND_WAIT_MS + MIN_TURN_MS) {
          reports.push(`[${commands.length} command(s) were not run — this task ran out of turns or time.]`);
          break;
        }

        // Boot the executor once per task, and only when a command is actually
        // wanted. A task that never runs anything must not pay for a VM.
        if (executorReady === null) {
          try {
            await ctx.runAction(internal.githubActionsRunner.bootVmForBranch, { branchId: run.branchId });
            executorReady = true;
          } catch {
            executorReady = false;
          }
        }
        if (executorReady === false) {
          feedback = renderCommandsUnavailable("The command executor could not be started for this branch.");
          continue;
        }

        const ids = await ctx.runMutation(queueTaskCommandsRef, {
          branchId: run.branchId,
          taskId: args.taskId,
          agent,
          commands,
        });
        const outcomes = await waitForCommands(ctx, ids, Math.min(COMMAND_WAIT_MS, Math.max(remainingMs() - MIN_TURN_MS, 0)));
        feedback = outcomes.length > 0
          ? renderCommandResults(outcomes)
          : renderCommandsUnavailable("No executor picked the commands up in time.");
      }

      const report = [
        reports.join("\n\n"),
        wrote.size > 0 ? `Files written: ${[...wrote].join(", ")}` : "",
        removed.size > 0 ? `Files deleted: ${[...removed].join(", ")}` : "",
      ]
        .filter(Boolean)
        .join("\n\n");

      await ctx.runMutation(finishTaskRef, {
        runId: args.runId,
        taskId: args.taskId,
        status: "completed",
        result: report || "(the agent produced no output)",
      });
    } catch (err) {
      // A task stuck in "running" forever would stall the whole run — any
      // throw from the lookup, the model call, or a malformed response must
      // still reach finishTask so the task is marked terminal.
      const message = err instanceof Error ? err.message : String(err);
      await ctx.runMutation(finishTaskRef, {
        runId: args.runId,
        taskId: args.taskId,
        status: "failed",
        result: message,
      });
    }
  },
});

// Records a task's terminal outcome and re-enters dispatchReady so whatever
// it just unblocked starts without waiting for anything else to poll.
export const finishTask = internalMutation({
  args: {
    runId: v.id("codeRuns"),
    taskId: v.id("codeTasks"),
    status: v.union(v.literal("completed"), v.literal("failed")),
    result: v.string(),
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    const task = await ctx.db.get(args.taskId);
    if (!task) return; // deleted mid-flight — nothing left to finish
    await ctx.db.patch(args.taskId, { status: args.status, result: args.result, updatedAt: now });
    await ctx.db.insert("codeRunEvents", {
      runId: args.runId,
      taskId: args.taskId,
      type: args.status === "completed" ? "task.completed" : "task.failed",
      content: args.status === "completed" ? `"${task.title}" completed.` : `"${task.title}" failed: ${args.result}`,
      createdAt: now,
    });

    const run = await ctx.db.get(args.runId);
    if (!run) return;
    // Mirrors dispatchReady's own guard: cancellation must not be undone by a
    // task that happened to be in flight when it was requested.
    if (TERMINAL_RUN_STATUSES.has(run.status) || run.cancellationRequested) return;
    await ctx.scheduler.runAfter(0, dispatchReadyRef, { runId: args.runId });
  },
});
