// Code OS v2: durable run/task/event API. This is intentionally separate from
// the legacy pipeline so existing branches can migrate without data loss.
//
// This module is the parallel execution engine: unlike codePipeline.ts, which
// can only ever run one agent at a time because state lives on the single
// shared codeBranches row, every task here has its own row and its own
// status, so several can be "running" concurrently. Parallelism comes from
// scheduling one runTask action per ready task via ctx.scheduler.runAfter(0,
// ...) — never from Promise.all inside one action, which would risk the
// 10-minute action ceiling the moment two slow model calls land in the same
// invocation.
//
// Two things this engine does NOT do yet, on purpose:
// - {"op":"cmd"} command execution and MCP tool calls stay branch-scoped in
//   the live pipeline (codePipeline.ts). Porting them means giving a command
//   its own place to live outside the single branch "paused" flag, which is
//   future work, not this change.
// - Conflicting concurrent writes to the same underlying file are not
//   arbitrated. Convex mutations are transactional, so individual writes
//   still serialize, but two tasks racing on the same file is last-write-wins
//   exactly as it is in the live pipeline today. Known v1 limitation.
import { mutation, query, internalMutation, internalAction, internalQuery } from "./_generated/server";
import { makeFunctionReference } from "convex/server";
import { v } from "convex/values";
import type { Doc, Id } from "./_generated/dataModel";
import { assertBranchOwner, requireSession } from "./lib/codeAuth";
import { callModel } from "./lib/agentCore";
import { scheduleRun, type SchedulableTask } from "./lib/runScheduler";

// Self-references, made by string instead of through `internal.codeOrchestrator`
// — same fix as mcpServers.ts's refreshServerToolsRef. There the typed path
// trips the TS2589 instantiation-depth cliff; here it fails even earlier,
// because this module (added after the committed _generated/api.d.ts was last
// regenerated by `npx convex dev`) isn't in that generated type at all, so
// `internal.codeOrchestrator` is a flat TS2339 "does not exist". Either way
// the string path resolves identically at runtime and check-refs.mjs verifies
// it by name, kind and visibility just like a typed reference.
const dispatchReadyRef = makeFunctionReference<"mutation", { runId: Id<"codeRuns"> }>(
  "codeOrchestrator:dispatchReady",
);
const runTaskRef = makeFunctionReference<"action", { runId: Id<"codeRuns">; taskId: Id<"codeTasks"> }>(
  "codeOrchestrator:runTask",
);
const finishTaskRef = makeFunctionReference<
  "mutation",
  { runId: Id<"codeRuns">; taskId: Id<"codeTasks">; status: "completed" | "failed"; result: string }
>("codeOrchestrator:finishTask");
const getTaskContextRef = makeFunctionReference<
  "query",
  { runId: Id<"codeRuns">; taskId: Id<"codeTasks"> },
  { run: Doc<"codeRuns">; task: Doc<"codeTasks">; dependencies: Doc<"codeTasks">[] } | null
>("codeOrchestrator:getTaskContextInternal");

// Cap on tasks dispatched at once per run. Every concurrent task is a live
// model call, and the provider chain (lib/agentCore.ts) has shared rate
// limits and learned cooldowns (lib/providerCooldowns.ts) that apply
// platform-wide, across every run and the live pipeline — not per run. Letting
// one run's plan fan out without bound would hammer every seat at once and
// trip cooldowns for everything else sharing the chain. 4 keeps a single
// run's burst well inside what a free-tier seat tolerates.
const MAX_CONCURRENT_TASKS = 4;

const TERMINAL_RUN_STATUSES = new Set(["completed", "cancelled", "failed"]);

function toSchedulable(tasks: Doc<"codeTasks">[]): SchedulableTask[] {
  return tasks.map((t) => ({ id: t._id, status: t.status, dependencies: t.dependencies }));
}

export const startRun = mutation({
  args: {
    token: v.string(),
    branchId: v.string(),
    prompt: v.string(),
    permissionMode: v.optional(v.union(v.literal("ask"), v.literal("auto"), v.literal("read_only"))),
    // Optional model-authored plan. Ids are plain strings chosen by whatever
    // produced the plan (e.g. a Planner-style JSON output); they exist only to
    // express dependencies before real Convex ids exist and are translated
    // below.
    plan: v.optional(
      v.array(
        v.object({
          id: v.string(),
          title: v.string(),
          agent: v.optional(v.string()),
          dependencies: v.optional(v.array(v.string())),
        }),
      ),
    ),
  },
  handler: async (ctx, args) => {
    const session = await requireSession(ctx, args.token);
    const { branch } = await assertBranchOwner(ctx, session.userId, args.branchId);
    const now = Date.now();
    const runId = await ctx.db.insert("codeRuns", { branchId: args.branchId, projectId: branch.projectId, userId: session.userId, prompt: args.prompt.trim(), status: "queued", permissionMode: args.permissionMode ?? "ask", createdAt: now, updatedAt: now });

    if (args.plan && args.plan.length > 0) {
      // Pass 1: insert every task so a real Convex id exists for each plan
      // entry, then pass 2 translates each entry's string-id dependencies into
      // those real ids. An entry naming a dependency id outside the plan is
      // dropped rather than failing the insert — a typo in a model-authored
      // plan should not sink the run before it starts.
      const idMap = new Map<string, Id<"codeTasks">>();
      const inserted: { taskId: Id<"codeTasks">; dependsOn: string[] }[] = [];
      for (const entry of args.plan) {
        const taskId = await ctx.db.insert("codeTasks", {
          runId,
          title: entry.title,
          agent: entry.agent ?? "Analyser",
          status: "queued",
          dependencies: [],
          allowedTools: ["filesystem", "terminal", "mcp"],
          maxTurns: 12,
          createdAt: now,
          updatedAt: now,
        });
        idMap.set(entry.id, taskId);
        inserted.push({ taskId, dependsOn: entry.dependencies ?? [] });
      }
      for (const { taskId, dependsOn } of inserted) {
        const resolved = dependsOn
          .map((depId) => idMap.get(depId))
          .filter((id): id is Id<"codeTasks"> => id !== undefined);
        if (resolved.length > 0) await ctx.db.patch(taskId, { dependencies: resolved });
      }
      await ctx.db.insert("codeRunEvents", { runId, type: "run.created", content: `Run created with a ${args.plan.length}-task plan.`, createdAt: now });
      await ctx.scheduler.runAfter(0, dispatchReadyRef, { runId });
      return { runId, taskId: inserted[0].taskId, taskIds: inserted.map((i) => i.taskId) };
    }

    const taskId = await ctx.db.insert("codeTasks", { runId, title: "Understand and plan", agent: "Lead", status: "queued", dependencies: [], allowedTools: ["filesystem", "terminal", "mcp"], maxTurns: 12, createdAt: now, updatedAt: now });
    await ctx.db.insert("codeRunEvents", { runId, taskId, type: "run.created", content: "Run created and lead task queued.", createdAt: now });
    await ctx.scheduler.runAfter(0, dispatchReadyRef, { runId });
    return { runId, taskId };
  },
});

export const listRuns = query({ args: { token: v.string(), branchId: v.string() }, handler: async (ctx, args) => {
  const session = await requireSession(ctx, args.token); await assertBranchOwner(ctx, session.userId, args.branchId);
  return await ctx.db.query("codeRuns").withIndex("by_branch", q => q.eq("branchId", args.branchId)).order("desc").take(50);
} });

export const getRunBoard = query({ args: { token: v.string(), runId: v.id("codeRuns") }, handler: async (ctx, args) => {
  const session = await requireSession(ctx, args.token); const run = await ctx.db.get(args.runId); if (!run || run.userId !== session.userId) return null;
  const [tasks, events] = await Promise.all([ctx.db.query("codeTasks").withIndex("by_run", q => q.eq("runId", args.runId)).collect(), ctx.db.query("codeRunEvents").withIndex("by_run", q => q.eq("runId", args.runId)).order("desc").take(100)]);
  return { run, tasks, events: events.reverse() };
} });

export const cancelRun = mutation({ args: { token: v.string(), runId: v.id("codeRuns") }, handler: async (ctx, args) => {
  const session = await requireSession(ctx, args.token); const run = await ctx.db.get(args.runId); if (!run || run.userId !== session.userId) throw new Error("Run not found"); const now = Date.now();
  await ctx.db.patch(run._id, { status: "cancelled", cancellationRequested: true, updatedAt: now });
  await ctx.db.insert("codeRunEvents", { runId: run._id, type: "run.cancelled", content: "Cancelled by user.", createdAt: now });
} });

// Loads a run and its tasks, asks lib/runScheduler which tasks are ready to
// run right now, and acts on that decision. Re-entered by finishTask every
// time a task completes, which is what actually drives a run to completion —
// each dispatch only starts what is newly unblocked.
export const dispatchReady = internalMutation({
  args: { runId: v.id("codeRuns") },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (!run) return;
    // A terminal run is done; a cancelled-but-not-yet-terminal run must not
    // pick up new work either — cancelRun already stamped both status and
    // cancellationRequested together, but this checks both defensively so a
    // future caller that sets one without the other still can't resurrect it.
    if (TERMINAL_RUN_STATUSES.has(run.status) || run.cancellationRequested) return;

    const tasks = await ctx.db.query("codeTasks").withIndex("by_run", (q) => q.eq("runId", args.runId)).collect();
    const byId = new Map<string, Doc<"codeTasks">>();
    for (const t of tasks) byId.set(t._id, t);

    const decision = scheduleRun(toSchedulable(tasks), {
      maxConcurrent: MAX_CONCURRENT_TASKS,
      cancellationRequested: run.cancellationRequested ?? false,
    });
    const now = Date.now();

    for (const id of decision.ready) {
      const task = byId.get(id);
      if (task) await ctx.db.patch(task._id, { status: "running", updatedAt: now });
    }
    for (const id of decision.block) {
      const task = byId.get(id);
      if (task) await ctx.db.patch(task._id, { status: "blocked", updatedAt: now });
    }
    for (const id of decision.ready) {
      const task = byId.get(id);
      if (task) await ctx.scheduler.runAfter(0, runTaskRef, { runId: args.runId, taskId: task._id });
    }

    await ctx.db.insert("codeRunEvents", {
      runId: args.runId,
      type: "run.dispatch",
      content: `Dispatched ${decision.ready.length} task(s); blocked ${decision.block.length}.`,
      createdAt: now,
    });

    if (decision.stuck) {
      // A deadlocked run (dependencies that can never all be satisfied, or a
      // cycle) must end loudly, never sit at "running" with nothing in
      // flight forever.
      await ctx.db.patch(run._id, { status: "failed", updatedAt: now });
      await ctx.db.insert("codeRunEvents", {
        runId: args.runId,
        type: "run.stuck",
        content: `Run deadlocked — no task can make progress. Stuck task ids: ${decision.stuckIds.join(", ") || "(none)"}.`,
        createdAt: now,
      });
      return;
    }

    await ctx.db.patch(run._id, { status: decision.runStatus, updatedAt: now });

    // A blocking cascade has to be driven, not just started. finishTask is the
    // only other thing that re-enters this mutation, and a blocked task never
    // finishes — so a dispatch that blocked tasks without starting any would
    // be the last one to ever run. Left there, a failure's grandchildren stay
    // "queued" forever under a run still reading "running" with nothing in
    // flight, which is precisely the hang the stuck branch above exists to
    // prevent, reached by the other path. runScheduler resolves one dependency
    // level per call by design, so the loop has to come from here.
    if (decision.block.length > 0) {
      await ctx.scheduler.runAfter(0, dispatchReadyRef, { runId: args.runId });
    }
  },
});

// Read-only lookup an action needs to build a task's prompt: the run, the
// task itself, and the completed dependency tasks whose results feed it.
export const getTaskContextInternal = internalQuery({
  args: { runId: v.id("codeRuns"), taskId: v.id("codeTasks") },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    const task = await ctx.db.get(args.taskId);
    if (!run || !task || task.runId !== args.runId) return null;
    const dependencies = (await Promise.all(task.dependencies.map((id) => ctx.db.get(id)))).filter(
      (d): d is Doc<"codeTasks"> => d !== null,
    );
    return { run, task, dependencies };
  },
});

// Executes exactly one task's agent turn. This is the unit of concurrency:
// dispatchReady schedules one of these per ready task, so N scheduled actions
// is how N tasks actually run at the same time.
export const runTask = internalAction({
  args: { runId: v.id("codeRuns"), taskId: v.id("codeTasks") },
  handler: async (ctx, args) => {
    try {
      const context = await ctx.runQuery(getTaskContextRef, args);
      if (!context) return; // run or task vanished (e.g. deleted mid-flight) — nothing to execute
      const { run, task, dependencies } = context;

      const upstream = dependencies.length > 0
        ? dependencies.map((d) => `### Result from "${d.title}" (${d.agent})\n${d.result ?? "(no result recorded)"}`).join("\n\n")
        : "(no dependencies — this is a starting task)";
      const prompt = `Overall goal: ${run.prompt}\n\nYour task: ${task.title}\n\nResults from the tasks this depends on:\n${upstream}`;
      const systemPrompt = `You are the ${task.agent} agent, executing one task inside a larger multi-agent run. Complete only the task described below and report your result in clear prose.`;

      const result = await callModel(prompt, systemPrompt, task.agent, ctx);
      await ctx.runMutation(finishTaskRef, {
        runId: args.runId,
        taskId: args.taskId,
        status: "completed",
        result: result.text,
      });
    } catch (err) {
      // A task stuck in "running" forever would stall the whole run — any
      // throw from the lookup, the model call, or a malformed response must
      // still reach finishTask so the task is marked terminal.
      const message = err instanceof Error ? err.message : String(err);
      await ctx.runMutation(finishTaskRef, {
        runId: args.runId,
        taskId: args.taskId,
        status: "failed",
        result: message,
      });
    }
  },
});

// Records a task's terminal outcome and re-enters dispatchReady so whatever
// it just unblocked starts without waiting for anything else to poll.
export const finishTask = internalMutation({
  args: {
    runId: v.id("codeRuns"),
    taskId: v.id("codeTasks"),
    status: v.union(v.literal("completed"), v.literal("failed")),
    result: v.string(),
  },
  handler: async (ctx, args) => {
    const now = Date.now();
    const task = await ctx.db.get(args.taskId);
    if (!task) return; // deleted mid-flight — nothing left to finish
    await ctx.db.patch(args.taskId, { status: args.status, result: args.result, updatedAt: now });
    await ctx.db.insert("codeRunEvents", {
      runId: args.runId,
      taskId: args.taskId,
      type: args.status === "completed" ? "task.completed" : "task.failed",
      content: args.status === "completed" ? `"${task.title}" completed.` : `"${task.title}" failed: ${args.result}`,
      createdAt: now,
    });

    const run = await ctx.db.get(args.runId);
    if (!run) return;
    // Mirrors dispatchReady's own guard: cancellation must not be undone by a
    // task that happened to be in flight when it was requested.
    if (TERMINAL_RUN_STATUSES.has(run.status) || run.cancellationRequested) return;
    await ctx.scheduler.runAfter(0, dispatchReadyRef, { runId: args.runId });
  },
});
